import styles from "./index.module.css";
import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.container}>
          <h1 className={styles.title}>
            Https <span className={styles.pinkSpan}>T3</span> Redirect
          </h1>
          <div className={styles.cardRow}>
            <Link
              className={styles.card}
              href="/dashboard"
              target="_blank"
            >
              <h3 className={styles.cardTitle}>Ir al dashboard →</h3>
              <div className={styles.cardText}>
                testeando redirect desde http a http con next
              </div>
            </Link>
          </div>
        </div>
      </main>
    </>
  );
};

export default Home;
